#!/usr/bin/env bash
# This script is displaying "display hours from 0 to 12" and "display minutes from 1 to 59"
i=1
j=0
while [ "$j" -le 12 ]
do
    echo "Hour: $j"
    i=1
    while [ "$i" -le 59 ]
    do
        echo "$i"
	i=$((i + 1))
    done
    j=$((j + 1))
done
i=$i
